"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
	async up(queryInterface, Sequelize) {
		await queryInterface.bulkInsert(
			"Movies",
			[
				{
					title: "Autogenerated first art piece",
					imageURL:
						"https://upload.wikimedia.org/wikipedia/commons/6/6b/A_page_from_Collection_of_Reproductions_of_Medallions_by_Phoebe_Anna_Traquair.jpg",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					title: "Autogenerated second art piece",
					imageURL:
						"https://upload.wikimedia.org/wikipedia/commons/a/ad/%22Nr118%22_2023.jpg",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
			],
			{}
		);
	},

	async down(queryInterface, Sequelize) {},
};
